name: CI

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
on:
  push:
    branches: [ main ]
    paths:
      - src/**
      - .github/workflows/ci.yml
  pull_request:
    branches: [ main ]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/JosephJShort/Jodo.Extensions
            azure-pipeline-name: 'Jodo.Extensions-CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
