name: Tests

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
on:
  push:
    branches: [ main ]
    paths:
      - src/**
      - .github/workflows/tests.yml
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
